version: '3.1'

services:
  apache:
    env_file: .env
    image: httpd:2.4
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    links:
      - db
  
  wordpress:
    depends_on:
      - db
    env_file: .env
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: gatita12
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php

  db:
    image: mariadb:10.5  # Usando MariaDB en lugar de MySQL
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: gatita12
      MYSQL_ROOT_PASSWORD: gatita12  # En lugar de MYSQL_RANDOM_ROOT_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
  apache:
