version: '3.1'

services:
  apache:
    env_file: .env
    image: httpd:${HTTPD_VERSION}
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
    links:
      - db
      
  wordpress:
    depends_on:
      - db
    env_file: .env
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}  
      WORDPRESS_DB_USER: ${DB_USERNAME}  
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD} 
      WORDPRESS_DB_NAME: ${DB_DATABASE} 

  db:
    image: mariadb:${DB_VERSION}  
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}  
      MYSQL_USER: ${DB_USERNAME}  
      MYSQL_PASSWORD: ${DB_PASSWORD}  
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
      
volumes:
  wordpress:
  db:
  apache:
